### ISSUE TITLE
Log constraints for debug purpose

### ISSUE THREAD

**Issue by arnaud-secondlayer** [google/cassowary.dart#22]
When I create a constraint and print it to logs I end up with something like:
```
+Instance of 'Variable' >= 0  | priority = 1000000000.0 (required)
```

This happens even after I set a `name` to the variable. Is there a way to get variable names when printing constraints?
I looked at the `Variable` class and `toString()` is not implemented.

**Comment by domesticmouse** [comment]
Feel free to submit a PR with the changes. Please add test to stop regressions. Thanks!
